### ISSUE TITLE
Semana 2

### ISSUE THREAD

**Issue by carrz** [carrz/card-validator#3]
- [x] Validar que los datos ingresados en el campo Número de tarjeta sean sólo números. (Bianca)
- [x] Validar que los datos ingresados en el campo Fecha de vencimiento sean números en formato fecha (meses hasta el 12, años desde el 2018 hasta el 2050(?)). (Carla)
- [x] Validar que los datos ingresados en el campo Código de validación sean sólo números. (Bianca)
- [x] Validar que los datos ingresados en el campo Nombre sean sólo letras. (Carla)
- [x] Agregarle la clase .error a los input que no pasen la validación. (Bianca)
- [x] Agregarle la clase .success a los input que pasen la validación. (Carla)

**Comment by byanezzz** [comment]
Se realizaron los Test para la función de validación de datos numéricos.
Se realizó también la función que permite filtrar que los datos ingresados en los campos numéricos, sean sólo números.
